version: '3'
services:
  web:
    build: .
    container_name: web
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db
      - SECRET_KEY_BASE=123321
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:10.6
    container_name: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myapp_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data