default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5

staging:
  <<: *default
  database: myapp_staging

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test